# Generated by Django 4.2.4 on 2023-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_lineapedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparado', 'Preparado'), ('enviado', 'Enviado'), ('recogido', 'Recogido'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
    ]
