# Generated by Django 4.2.4 on 2023-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagen_rename_imagen_post_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduccion',
            field=models.CharField(default='Introduccion', max_length=50),
        ),
    ]
